server:
  port: 8989

spring:
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1d
  redis:
    host: 127.0.0.1
    port: 6379
    # 密码 没有则可以不填
    password:
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1

custom:
  socket:
    max-content-length: 2147483647
    connect-timeout-millis: 3000
    proxy-port: 8088
    client-thread-num: 2
    event-thread-num: 4

